# Generated by Django 5.1.4 on 2025-01-15 08:11

import django.core.validators
import django.db.models.deletion
import pendaftaran.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_npm', message='NPM hanya boleh berisi angka.', regex='^\\d+$')])),
                ('email_aktif', models.EmailField(max_length=100)),
                ('nomor_wa', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor WA harus berupa angka, minimal 10 digit.', regex='^\\+?\\d{10,15}$')])),
                ('strata', models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50)),
                ('program_studi', models.CharField(choices=[('sosiologi', 'Sosiologi'), ('ilmu_pemerintahan', 'Ilmu Pemerintahan'), ('ilmu_komunikasi', 'Ilmu Komunikasi'), ('administrasi_negara', 'Administrasi Negara'), ('ilmu_administrasi_bisnis', 'Ilmu Administrasi Bisnis'), ('hubungan_internasional', 'Hubungan Internasional'), ('administrasi_perkantoran', 'Administrasi Perkantoran'), ('hubungan_masyarakat', 'Hubungan Masyarakat'), ('perpustakaan', 'Perpustakaan'), ('magister_ilmu_pemerintahan', 'Magister Ilmu Pemerintahan'), ('magister_ilmu_komunikasi', 'Magister Ilmu Komunikasi'), ('magister_ilmu_administrasi', 'Magister Ilmu Administrasi'), ('studi_pembangunan', 'Studi Pembangunan')], max_length=50)),
                ('periode_wisuda', models.CharField(choices=[('periode_I', 'Periode I'), ('periode_II', 'Periode II'), ('periode_III', 'Periode III'), ('periode_IV', 'Periode IV'), ('periode_V', 'Periode V'), ('periode_VI', 'Periode VI'), ('periode_VII', 'Periode VII')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_npm', message='NPM hanya boleh berisi angka.', regex='^\\d+$')])),
                ('email_aktif', models.EmailField(max_length=254)),
                ('nomor_wa', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor WA harus berupa angka, minimal 10 digit.', regex='^\\+?\\d{10,15}$')])),
                ('strata', models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50)),
                ('program_studi', models.CharField(choices=[('sosiologi', 'Sosiologi'), ('ilmu_pemerintahan', 'Ilmu Pemerintahan'), ('ilmu_komunikasi', 'Ilmu Komunikasi'), ('administrasi_negara', 'Administrasi Negara'), ('ilmu_administrasi_bisnis', 'Ilmu Administrasi Bisnis'), ('hubungan_internasional', 'Hubungan Internasional'), ('administrasi_perkantoran', 'Administrasi Perkantoran'), ('hubungan_masyarakat', 'Hubungan Masyarakat'), ('perpustakaan', 'Perpustakaan'), ('magister_ilmu_pemerintahan', 'Magister Ilmu Pemerintahan'), ('magister_ilmu_komunikasi', 'Magister Ilmu Komunikasi'), ('magister_ilmu_administrasi', 'Magister Ilmu Administrasi'), ('studi_pembangunan', 'Studi Pembangunan')], max_length=50)),
                ('periode_wisuda', models.CharField(choices=[('periode_I', 'Periode I'), ('periode_II', 'Periode II'), ('periode_III', 'Periode III'), ('periode_IV', 'Periode IV'), ('periode_V', 'Periode V'), ('periode_VI', 'Periode VI'), ('periode_VII', 'Periode VII')], max_length=50)),
                ('user', models.OneToOneField(default=pendaftaran.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Berkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_berkas', models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], max_length=50)),
                ('file', models.FileField(upload_to='berkas/', validators=[pendaftaran.models.validate_file_extension, pendaftaran.models.validate_file_size])),
                ('pendaftar', models.ForeignKey(default=pendaftaran.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='berkas_set', to='pendaftaran.pendaftar')),
            ],
        ),
    ]
