# Generated by Django 5.1.4 on 2024-12-31 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('jenis_berkas', models.CharField(choices=[('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah')], max_length=50)),
                ('status', models.CharField(default='Menunggu Verifikasi', max_length=20)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
