# Generated by Django 5.1.4 on 2025-01-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_berkas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=15)),
                ('email_aktif', models.EmailField(max_length=254)),
                ('strata', models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], max_length=50)),
                ('program_studi', models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], max_length=100)),
                ('periode_wisuda', models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='berkas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='berkas',
            name='tanggal_upload',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='nomor_mahasiswa',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='tanggal_daftar',
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='npm',
            field=models.CharField(default='00000000', max_length=15),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='periode_wisuda',
            field=models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], default='2025-01', max_length=100),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='program_studi',
            field=models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], default='Sistem Informasi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='strata',
            field=models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], default='Masukan Strata', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='berkas',
            name='file',
            field=models.FileField(upload_to='berkas/'),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='jenis_berkas',
            field=models.CharField(choices=[('foto', 'Foto hitam putih dengan latar putih'), ('ktm', 'Kartu Tanda Mahasiswa'), ('skpi', 'Surat Keterangan Pendamping Ijazah'), ('ukt', 'Bukti Pembayaran UKT'), ('judul', 'Judul dan Pengesahan TA/Skripsi/Disertasi'), ('usul', 'Berita Acara Seminar Usul'), ('ujian', 'Berita Acara Ujian TA/Skripsi/Disertasi'), ('tatib', 'Surat Pernyataan Tata Tertib Wisudawan'), ('ept_toefl', 'Sertifikat EPT/Toefl'), ('bebas_perpus_ruang_baca', 'Bukti Bebas Pinjam Ruang Baca FISIP dan UPT Perpustakaan Unila'), ('upload_sebar', 'Bukti Upload dan Sebar'), ('ijazah', 'Ijazah SLTA/D3/S1/S2'), ('sk_pembimbing', 'SK Pembimbing'), ('sk_penguji', 'SK Penguji')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
