# Generated by Django 5.1.4 on 2025-01-08 02:04

import django.core.validators
import pendaftaran.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_mahasiswa_remove_berkas_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkas',
            name='file',
            field=models.FileField(upload_to='berkas/', validators=[pendaftaran.models.validate_file_extension, pendaftaran.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_npm', message='NPM hanya boleh berisi angka.', regex='^\\d+$')]),
        ),
    ]
