# Generated by Django 5.1.4 on 2025-01-08 08:15

import django.core.validators
import pendaftaran.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0004_alter_berkas_file_alter_mahasiswa_npm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftar',
            name='password',
            field=models.CharField(default='temporarypassword', max_length=128, validators=[pendaftaran.models.validate_password]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_npm', message='NPM hanya boleh berisi angka.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='periode_wisuda',
            field=models.CharField(choices=[('periode_I', 'Periode I'), ('periode_II', 'Periode II'), ('periode_III', 'Periode III'), ('periode_IV', 'Periode IV'), ('periode_V', 'Periode V'), ('periode_VI', 'Periode VI'), ('periode_VII', 'Periode VII')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='program_studi',
            field=models.CharField(choices=[('sosiologi', 'Sosiologi'), ('ilmu_pemerintahan', 'Ilmu Pemerintahan'), ('ilmu_komunikasi', 'Ilmu Komunikasi'), ('administrasi_negara', 'Administrasi Negara'), ('ilmu_administrasi_bisnis', 'Ilmu Administrasi Bisnis'), ('hubungan_internasional', 'Hubungan Internasional'), ('administrasi_perkantoran', 'Administrasi Perkantoran'), ('hubungan_masyarakat', 'Hubungan Masyarakat'), ('perpustakaan', 'Perpustakaan'), ('magister_ilmu_pemerintahan', 'Magister Ilmu Pemerintahan'), ('magister_ilmu_komunikasi', 'Magister Ilmu Komunikasi'), ('magister_ilmu_administrasi', 'Magister Ilmu Administrasi'), ('studi_pembangunan', 'Studi Pembangunan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='strata',
            field=models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='npm',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_npm', message='NPM hanya boleh berisi angka.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='periode_wisuda',
            field=models.CharField(choices=[('periode_I', 'Periode I'), ('periode_II', 'Periode II'), ('periode_III', 'Periode III'), ('periode_IV', 'Periode IV'), ('periode_V', 'Periode V'), ('periode_VI', 'Periode VI'), ('periode_VII', 'Periode VII')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='program_studi',
            field=models.CharField(choices=[('sosiologi', 'Sosiologi'), ('ilmu_pemerintahan', 'Ilmu Pemerintahan'), ('ilmu_komunikasi', 'Ilmu Komunikasi'), ('administrasi_negara', 'Administrasi Negara'), ('ilmu_administrasi_bisnis', 'Ilmu Administrasi Bisnis'), ('hubungan_internasional', 'Hubungan Internasional'), ('administrasi_perkantoran', 'Administrasi Perkantoran'), ('hubungan_masyarakat', 'Hubungan Masyarakat'), ('perpustakaan', 'Perpustakaan'), ('magister_ilmu_pemerintahan', 'Magister Ilmu Pemerintahan'), ('magister_ilmu_komunikasi', 'Magister Ilmu Komunikasi'), ('magister_ilmu_administrasi', 'Magister Ilmu Administrasi'), ('studi_pembangunan', 'Studi Pembangunan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='strata',
            field=models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50),
        ),
    ]
