# Generated by Django 5.1.4 on 2025-01-13 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0006_pendaftar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendaftar',
            old_name='email',
            new_name='email_aktif',
        ),
        migrations.RenameField(
            model_name='pendaftar',
            old_name='nama',
            new_name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='password',
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='nomor_wa',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor WA harus berupa angka, minimal 10 digit.', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
